### ISSUE TITLE
Hello, is there maybe a wiki on how to run it?

### ISSUE THREAD

**Issue by yanelev** [zalopage/Zalo-Sdk-Php#1]

**Comment by hoangthienan** [comment]
You can find out more information at [http://developer.page.zaloapp.com/php?act=gt](http://developer.page.zaloapp.com/php?act=gt)

**Comment by yanelev** [comment]
That one is great but how to obtain the $pageId, $secretKey?

**Comment by yanelev** [comment]
Is there a way to fill out these details
$pageId = 0; //fill your page 's id here
    $secretKey = ""; //fill your page 's secret key here
    $toUid = 0; //fill user 'id, you want to send message

**Comment by hoangthienan** [comment]
after registering an account Zalo, then register Zalo Page, you will key pair

http://page.zaloapp.com/

**Comment by yanelev** [comment]
Thank you I will try
