### ISSUE TITLE
How to get secretKey ?

### ISSUE THREAD

**Issue by jacksnow00** [zalopage/Zalo-Sdk-Php#2]
Hi, is this the official Zalo Page SDK ?
so I visited http://zms.apitoy.com/ and 
http://developer.page.zaloapp.com/ 
but I dont see anywhere to get the key ?

**Comment by hoangthienan** [comment]
This repo unofficial Zalo Php SDk,  
current to get the pageId and secretKey, you need to contact us directly with support Zalo

Ps: sorry, I just spent the summer holidays
